### ISSUE TITLE
Review `CREATE STREAM` and `CREATE MATERIALIZED VIEW` syntax 

### ISSUE THREAD

**Issue by jfallows** [aklivity/zillabase#128]
**Describe the desired outcome from the user's perspective**
As appdev, I want to create request-response APIs via zillabase simply in SQL.

**Acceptance criteria**
 - Map as closely as possible to existing concepts
 - Minimize introduction of zilla-specific complexity if possible

**Additional context**
Consider syntax such as `CREATE ZSTREAM ...` and `CREATE ZSTREAM ... WITH ( reply_to= ... }` etc.
Consider syntax such as `CREATE ZTABLE ...` to implicitly trigger source and sync to Kafka.
Consider syntax such as `CREATE ZVIEW ...` to implicitly trigger sync only to Kafka.

This implies `SHOW ZSTREAMS`, `SHOW ZTABLES` and `SHOW ZVIEWS`.

Consider syntax `CREATE TABLE ...` to pass through without implicitly triggering source and sync to Kafka.

Note: in each case with `Z` prefix, it represents an API we expose via Zillabase.

**Tasks**

- [x] Update schemas to catalog z related queries into a separate schema and make public schema as defaul
- [x] Support `ZSTREAM`, `ZVIEW`, and  `ZTABLE` syntax
- [x] Enhance `ZSTREAM` to support `reply_to`
- [x] Support identity filtering in  `ZSTREAM`, `ZVIEW`, and  `ZTABLE` queries
